#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/keysymdef.h>
#include "IMdkit.h"
#include "Xi18n.h"

/* Trigger Keys List */
static XIMTriggerKey Trigger_Keys[] = {
  {XK_Shift_L, ControlMask, ControlMask},
  {XK_Shift_R, ControlMask, ControlMask},
  {XK_A, 0, ControlMask | Mod1Mask},
  {XK_a, 0, ControlMask | Mod1Mask},
  {XK_B, 0, ControlMask | Mod1Mask},
  {XK_b, 0, ControlMask | Mod1Mask},
  {XK_C, 0, ControlMask | Mod1Mask},
  {XK_c, 0, ControlMask | Mod1Mask},
  {XK_D, 0, ControlMask | Mod1Mask},
  {XK_d, 0, ControlMask | Mod1Mask},
  {XK_E, 0, ControlMask | Mod1Mask},
  {XK_e, 0, ControlMask | Mod1Mask},
  {XK_F, 0, ControlMask | Mod1Mask},
  {XK_f, 0, ControlMask | Mod1Mask},
  {XK_G, 0, ControlMask | Mod1Mask},
  {XK_g, 0, ControlMask | Mod1Mask},
  {XK_H, 0, ControlMask | Mod1Mask},
  {XK_h, 0, ControlMask | Mod1Mask},
  {XK_I, 0, ControlMask | Mod1Mask},
  {XK_i, 0, ControlMask | Mod1Mask},
  {XK_K, 0, ControlMask | Mod1Mask},
  {XK_k, 0, ControlMask | Mod1Mask},
  {XK_L, 0, ControlMask | Mod1Mask},
  {XK_l, 0, ControlMask | Mod1Mask},
  {XK_M, 0, ControlMask | Mod1Mask},
  {XK_m, 0, ControlMask | Mod1Mask},
  {XK_N, 0, ControlMask | Mod1Mask},
  {XK_n, 0, ControlMask | Mod1Mask},
  {XK_O, 0, ControlMask | Mod1Mask},
  {XK_o, 0, ControlMask | Mod1Mask},
  {XK_P, 0, ControlMask | Mod1Mask},
  {XK_p, 0, ControlMask | Mod1Mask},
  {XK_Q, 0, ControlMask | Mod1Mask},
  {XK_q, 0, ControlMask | Mod1Mask},
  {XK_R, 0, ControlMask | Mod1Mask},
  {XK_r, 0, ControlMask | Mod1Mask},
  {XK_S, 0, ControlMask | Mod1Mask},
  {XK_s, 0, ControlMask | Mod1Mask},
  {XK_T, 0, ControlMask | Mod1Mask},
  {XK_t, 0, ControlMask | Mod1Mask},
  {XK_U, 0, ControlMask | Mod1Mask},
  {XK_u, 0, ControlMask | Mod1Mask},
  {XK_V, 0, ControlMask | Mod1Mask},
  {XK_v, 0, ControlMask | Mod1Mask},
  {XK_W, 0, ControlMask | Mod1Mask},
  {XK_w, 0, ControlMask | Mod1Mask},
  {XK_X, 0, ControlMask | Mod1Mask},
  {XK_x, 0, ControlMask | Mod1Mask},
  {XK_Y, 0, ControlMask | Mod1Mask},
  {XK_y, 0, ControlMask | Mod1Mask},
  {XK_Z, 0, ControlMask | Mod1Mask},
  {XK_z, 0, ControlMask | Mod1Mask}
};
